### PR TITLE
Update UserService.go - adding "getUserKeys" command

### PR DESCRIPTION
**Pull request by rustsind**
Hi,

I've added "getUserKeys" command. 

Only difference from original pattern/style of code is nested response structs, without such  Unmarshal just return empty struct with no error.

### CODE REVIEW

**Comment by svanharmelen** [comment]
Thanks for the PR @rustsind!

Unfortunately I cannot merge the PR as is, as the code in this package is automatically generated by the [generate](https://github.com/xanzy/go-cloudstack/tree/master/generate) package. The input for the generation is the output of the `listApis` API call which is saved to the [api.go](https://github.com/xanzy/go-cloudstack/blob/master/generate/api.go) file.

So if this is a new function that is currently not in this package, I guess we need to update the content of `api.go` and generate the code again...

**Comment by rustsind** [comment]
@svanharmelen,
I couldn't find find this function in your package, I believe it's because "getUserKeys" appeared only in [Cloudstack API v4.10](http://cloudstack.apache.org/api/apidocs-4.10/).
I would really appreciate if you could spend your time for this task and regenerate code to prevent problems in future releases. :)

**Comment by svanharmelen** [comment]
@rustsind if you are able to send me the (JSON formatted) output of the `listApis` call (against an CS 4.10 instance), I can fix this for you...

**Comment by svanharmelen** [comment]
@rustsind I would like to close this one, but then I would need the JSON output of a `listApis` call. If you are able to provide it, I'll make sure to update the package with it... Thx!

**Comment by svanharmelen** [comment]
Closing this due to a lack of response, Feel free to reopen this whenever you want to work on this again...

**Pull request closed without merging**
