### PR TITLE
added an envirionment variable to specify http method

### PR DESCRIPTION
**Pull request by atsaki**
This patch enable to use GET method for deployVirtualMachine and updateVirtualMachine.

POST is used for deployVirtualMachine and updateVirtualMachine by default. If an environment variable ```GO_CLOUDSTACK_ALWAYS_USE_GET=1```, GET is used for them.

Although CloudStack API accepts GET and POST method, some service providers' API does not accept POST method. It seems that they implement their own API proxy and they can not accept POST method.
This patch allows us to use tools using go-cloudstack (ex. Terraform, docker machine) on such service providers.

### CODE REVIEW

**Comment by svanharmelen** [comment]
@atsaki thanks for the PR, but as the packages are auto generated any changes that need to persist should be made in the `generate` package instead of to the generated packages.

Next to that I fully understand what you are trying to achieve, but I'm not sure if this is the correct way of doing it. The `go-cloudstack` package should be used as a library package by other projects and it should be transparent for the end users. So I think it would be much cleaner if we can make this a configurable option of the (async-)client. It would then need an additional option in Terraform and Docker Machine using the "normal" configs used by those packages.

Will have a look at implementing something like that. In the mean to I woud very much like to know which providers are not allowing the POST calls to be made to their CloudStack API? So would be thankful if you can share the once you know about!

Cheers,

Sander

**Comment by atsaki** [comment]
@svanharmelen thanks for your comment.

> @atsaki thanks for the PR, but as the packages are auto generated any changes that need to persist should be made in the generate package instead of to the generated packages.

I changed generate package to persist changes.

> Next to that I fully understand what you are trying to achieve, but I'm not sure if this is the correct way of doing it. The go-cloudstack package should be used as a library package by other projects and it should be transparent for the end users. So I think it would be much cleaner if we can make this a configurable option of the (async-)client.

I admit this is a somewhat dirty way of doing it. I can understand it would be cleaner HTTP method is configured by option of the client. But I think using an environmental variable is one of the way to configure HTTP method. The benefit of using an environmental variable is we can switch GET/POST method without any change of code of tools. It is very hard to implement an additional option to configure HTTP method for each existing or new tools. I would like to have an option to use tools using this library easily without any code changes.

> In the mean to I woud very much like to know which providers are not allowing the POST calls to be made to their CloudStack API? So would be thankful if you can share the once you know about!

One of such provier is IDC Frontier I am belonging to. It is a hard work to fix the implementation and takes some time. I am very happy if we can use tools like Terraform and Docker machine with our provider and contribute to develop them as soon as possible.

I think It is good to have some way to configure HTTP method whether it is using an environmental variable or not because CloudStack accept both method.

**Comment by svanharmelen** [comment]
@atsaki I thought about this one again, but I really don't think this is the best approach. If you are using Terraform and have a CloudStack cloud provider that only allows GET calls, you should be able to configure the Terraform CloudStack provider from within the Terraform config according to your needs.

As a Terraform enduser you shouldn't have to go in the source code and check what package is used internally by Terraform to talk to CloudStack in order to find out if there is a setting you can use to tweak it's behaviour. The tool you are using (Terraform, Docker Machine, ...) should give you the option to configure the tool according to your needs from within it's own config.

I believe this will greatly improve the user experience and so be a better solution...

So I'm going to close this PR, but in the mean time I updated the package (PRs #32 and #33) so this is now configurable in the client returned from the `NewClient` and `NewAsyncClient` calls. And I'm working on a little update for Terraform to expose the options as a configurable there as well, making Terraform work with your cloud provider. For Docker Machine you should do the same I suppose, which should really just be a couple of lines of code to implement...

Hope you can work with this as a solution to making this package usable for your cloud provider.

**Comment by atsaki** [comment]
@svanharmelen I understood the reason the case is closed. 
Thanks for updating the package #32, #33. I will update Docker Machine to add the options.

**Comment by svanharmelen** [comment]
@atsaki see PR https://github.com/hashicorp/terraform/pull/2753 for the implementation of this is TF.

The PR has a lot more, but there are a few lines that enable the config of the provider for GET calls only.

Cheers!

**Pull request closed without merging**
