### PR TITLE
Fix a bug in CreateSecurityGroup call

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by svanharmelen** [comment]
Thanks for the PR @mcanevet! I can however not merge this PR as all the code in this package is auto generated. So this means this info needs to be updated in a different location.

By may I ask on which version of CloudStack you tested this? Because it seems this is either changes or the `listApis` call does not reflect the result correctly. Both things are easy to fix, but just want to check it out first...

**Comment by mcanevet** [comment]
@svanharmelen I'm using Exoscale's Cloustack. I don't know how to check which version they are using.

**Comment by mcanevet** [comment]
It looks like they are using the API v4.4

**Comment by svanharmelen** [comment]
@mcanevet the issue is fixed and a new release is created (v2.1.4). So if you now update the dependency in your Terraform PR, we can start reviewing that one as well.

Thanks again for pointing this out!

**Pull request closed without merging**
