### PR TITLE
Fix bug while list capabilties

### PR DESCRIPTION
**Pull request by weizhouapache**
Different from other list commands, listcapabilities does not return an array list.

```
(localcloud) 🐱 > list capabilities
{
  "capability": {
    "allowusercreateprojects": true,
    "allowuserexpungerecovervm": true,
    "allowuserexpungerecovervolume": true,
    "allowuserviewalldomainaccounts": false,
    "allowuserviewdestroyedvm": true,
    "cloudstackversion": "4.15.0.0",
    "customdiskofferingmaxsize": 1024,
    "customdiskofferingminsize": 1,
    "dynamicrolesenabled": true,
    "kubernetesclusterexperimentalfeaturesenabled": false,
    "kubernetesserviceenabled": true,
    "kvmsnapshotenabled": true,
    "projectinviterequired": false,
    "regionsecondaryenabled": false,
    "securitygroupsenabled": false,
    "supportELB": "false",
    "userpublictemplateenabled": true
  }
}
```

for other list apis, e.g. list templates
```
(localcloud) 🐱 > list templates templatefilter=all filter=id,name
{
  "count": 2,
  "template": [
    {
      "id": "b54e8a17-ebe5-4849-a015-2698e1d01768",
      "name": "SystemVM Template (KVM)"
    },
    {
      "id": "63985306-48ee-11eb-8680-069fc4003392",
      "name": "CentOS 5.5(64-bit) no GUI (KVM)"
    }
  ]
}
```

### CODE REVIEW

**Comment by svanharmelen** [comment]
Hi @weizhouapache! All the code in the `cloudstack` package is generated by the code in the `generate` package. So making this change directly in the `cloudstack` package is not sustainable.

If your up for it, you can try to add the needed logic in the `generate` package, but if not I can have a look at that as well.

**Comment by weizhouapache** [comment]
@svanharmelen I will have a look at it and update you.

**Comment by weizhouapache** [comment]
@svanharmelen please review it !

**Comment by svanharmelen** [comment]
I updated the PR just a bit, but looks fine like this 👍🏻  Thanks @weizhouapache!

**Pull request merged**
