### PR TITLE
Allow overriding the default http client used in CS API requests

### PR DESCRIPTION
**Pull request by cezarsa**
This commit adds a method to simply replace the entire http client used for requests against the CS API. This could be useful for tweaking timeout values or even using a custom transport to log requests to the CS API.

### CODE REVIEW

**Comment by svanharmelen** [comment]
@cezarsa I think adding a more generic approach is maybe a better solution. Can you check/test if #116 solves your challenge?

**Comment by cezarsa** [comment]
Thanks @svanharmelen. I wasn't sure about what you would prefer as pattern for customizing the client so I went with the simpler solution. However, I think your solution is better and will make it easier adding further options in the future.
Closing in favor of #116.

**Comment by svanharmelen** [comment]
Did you have a change to double check the changes in #116?

**Comment by cezarsa** [comment]
No need for changes on #116, it works perfectly as is. I've just created a PR updating my code to the branch used in #116 and it works really well: https://github.com/tsuru/custom-cloudstack-ccm/pull/18/files#diff-e6bf6fd6123b13e2f45eaf8b1133c2d5R178

**Comment by svanharmelen** [comment]
Nice 👍🏻 Thanks for testing!

**Pull request closed without merging**
