### PR TITLE
Fix security group on security group

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by svanharmelen** [comment]
@mcanevet could you help me understand this PR? I noticed the same logic in your previous PR, but assumed it was typed that way just to illustrate that the key and the value should be the actual values, instead of having a set of `key` and `value` labels holding the key and value.

What troubles me is that we are looping over a map of key and values but just overwrite the first (`[0]`) entry over and over. So no matter what you give as input, you will always end up with exactly 1 entry being the last value it looped over. And note that maps are unordered, so the last value will not be the same entry each time you run this.

Additionally if you only want 1 entry you just have to supply one entry in order to get this exact result... So please help me understand what you are trying to achieve and how you think it works?

**Comment by mcanevet** [comment]
At the end we want:
```
usersecuritygrouplist[0].account = "foo"
usersecuritygrouplist[0].group = "bar"
```
But your code will produce
```
usersecuritygrouplist[0].account = "foo"
usersecuritygrouplist[1].group = "bar"
```
The API is very weird on that point because it only uses the first entry of the array.
Actually in the API it's not a `map[string]string`, but a `[0]map[string]string`...

**Comment by svanharmelen** [comment]
Thanks, that clears things up... So this is actually a mapping between accounts and groups, right?

So what if we make it like this:

```go
  pn("	u.Set(fmt.Sprintf(\"%s[%%d].account\", i), k)", name)
  pn("	u.Set(fmt.Sprintf(\"%s[%%d].group\", i), vv)", name)
```

And were you call this you give it the account/group value like this:

```go
  m := make(map[string]string)
  m[ag.Account] = ag.Name
  param.SetUsersecuritygrouplist(m)
```

Think that would be a much cleaner solution... Thoughts?

**Comment by mcanevet** [comment]
Well it's not really a mapping between accounts and groups, I think it a quirk in the API.
The account should not appear here, it is just the account in cloudstack.
I'm not sure to explain it clearly, but you can see more explanation here : https://github.com/exoscale/cs/issues/5

**Comment by svanharmelen** [comment]
Yeah, I see that... But the solution I'm suggesting is providing a clean way to work with the quirk, right?

I generates the exact same thing that is shown in the example you pointed to, but with less static typed parts.

E.g. this:

```go
  m := make(map[string]string)
  m[ag.Account] = ag.Name
  param.SetUsersecuritygrouplist(m)
```

Versus this:

```go
  m := make(map[string]string)
  m["account"] = ag.Account
  m["group"] = ag.Name
  param.SetUsersecuritygrouplist(m)
```

So the solution would work as expected and solves your problem right (even though it might stay a quirky thing, but that's just how the CS API works)...

**Comment by mcanevet** [comment]
@svanharmelen ok, so the only thing I have to change is my terraform provider and keep go-cloudstack like that? If os, it's OK for me.

**Comment by svanharmelen** [comment]
Please see #68 this implements the fix as discussed here. So if you update your TF code to use this:

```go
  m := make(map[string]string)
  m[ag.Account] = ag.Name
  param.SetUsersecuritygrouplist(m)
```

Instead of this:

```go
  m := make(map[string]string)
  m["account"] = ag.Account
  m["group"] = ag.Name
  param.SetUsersecuritygrouplist(m)
```

All should be good for the new TF resource (once you updated the `go-cloudstack` dep to v2.1.5)

Thanks for your patience!

**Pull request closed without merging**
